categories = ["war", "nature", "wedding", "graduation", "cars", "art",
             "architecture","animation","anime","cartoon","travel","tourism",
             "food","style","pets","sports","events","figuers","journalist","news","men","women",
             "countries","palestine","ukraine","gaza","afghanistan","egypt","political","kuwait","graffiti","logo","zarqa",
             "music","movies","tv","games","technology","science","history","culture",
             "business","finance","economy","health","medicine","sports","fitness","lifestyle",
             "education","learning","school","college","university","students",
             "children","youth","adults","seniors","family","relationships",
             "friends","community","social","society","environment",
             "nature","wildlife","animal","plants","ecosystem",
             "climate","weather","earth","space","universe",
             "galaxy","stars","planets","solar system",
             "black hole","supernova","cosmic","astronomy",
             "physics","chemistry","biology","genetics",
             "mathematics","statistics","data","dog","wolf","human","fox","panda",
             "computer science","programming","software",
             "hardware","networking",
             "internet","web development",
             "mobile development",
             "artificial intelligence","machine learning",
             "deep learning","neural networks",
             "natural language processing",
             "computer vision",
             "robotics","automation",
             "internet of things",
             "blockchain","cryptocurrency",
             "virtual reality","augmented reality",
             "mixed reality","3D printing",
             "drones","unmanned aerial vehicles",
             "self-driving cars",
             "electric vehicles",'lion',
             "smart cities",
             "sustainable energy",
             "renewable energy",
             "solar power",
             "wind power","sports",
             "fitness","exercise","dragon ball","dragon"]