categories = [
            "war","tank","nature", "wedding", "graduation", "cars", "art",
            "architecture","animation","anime","cartoon","travel","tourism",
            "food","style","pets","sports","events","figuers","journalist","news","men","women",
            "countries","palestine","ukraine","gaza","afghanistan","egypt","political","kuwait","graffiti","logo","zarqa",
            "music","movies","tv","games","technology","science","history","culture",
            "business","finance","economy","health","medicine","sports","fitness","lifestyle","cat",
            "education","learning","school","college","university","students",
            "children","youth","adults","seniors","family","relationships",
            "friends","community","society","environment",
            "nature","wildlife","animal","plants","ecosystem",
            "climate","weather","earth","space","universe",
            "galaxy","stars","planets","solar system",
            "black hole","supernova","cosmic","astronomy",
            "physics","chemistry","biology","genetics",
            "mathematics","statistics","data","dog","wolf","human","fox","panda",
            "computer science","programming","software",
            "hardware","networking",
            "internet","web development",
            "mobile development",
            "artificial intelligence","machine learning",
            "deep learning","neural networks",
            "natural language processing",
            "computer vision",
            "robotics","automation",
            "internet of things",
            "blockchain","cryptocurrency",
            "virtual reality","augmented reality",
            "mixed reality","3D printing","desert",
            "drones","unmanned aerial vehicles",
            "self-driving cars",
            "electric vehicles",'lion',
            "smart cities",
            "sustainable energy",
            "renewable energy",
            "solar power",
            "wind power","sports",
            "fitness","exercise","dragon ball","dragon","violence", "blood", "gore","beach","winter","summer","bird","dragon","tower"
]
             
category_alias_map = {
        "war": ['tank', 'soldier', 'battle', 'explosion', 'ruins', 'military', 'gun', 'destroyed', 'army','gaza','rubble '],
        "graduation": ['graduation', 'cap', 'diploma', 'certificate', 'graduate','student', 'school', 'university'],
        "wedding": ['wedding', 'bride', 'groom', 'ring', 'ceremony', 'dress', 'cake'],
        "nature" :['tree', 'mountain', 'river', 'lake', 'sunset', 'forest', 'nature'],
        "tourism" : ['tourism', 'travel', 'landmark', 'beach', 'resort', 'hotel'],
        "architecture" : ['building', 'architecture', 'bridge', 'tower', 'skyscraper', 'monument'],
        "animal": ["dog", "cat", "lion", "elephant", "tiger", "bear", "horse", "fish", "bird", "rabbit", "kangaroo", "zebra", "giraffe", "panda"],
        "vehicle": ["car", "truck", "motorcycle", "bicycle", "bus", "train", "plane", "boat", "helicopter", "scooter"],
        "nature": ["forest", "mountain", "river", "ocean", "desert", "lake", "valley", "island", "canyon", "waterfall"],
        "technology": ["robot", "smartphone", "computer", "ai", "internet", "drone", "augmented reality", "virtual reality", "blockchain", "5g"],
        "food": ["pizza", "burger", "sushi", "pasta", "salad", "ice cream", "cake", "sandwich", "taco", "soup"],
        "sport": ["soccer", "basketball", "tennis", "baseball", "football", "hockey", "cricket", "rugby", "volleyball", "golf"],
        "music": ["rock", "pop", "jazz", "classical", "hip-hop", "blues", "country", "metal", "electronic", "reggae"],
        "art": ["painting", "sculpture", "photography", "drawing", "digital art", "graphic design", "ceramics", "architecture"],
        "fashion": ["clothing", "shoes", "accessories", "jewelry", "hat", "dress", "jeans", "jacket", "skirt"],
        "education": ["math", "history", "science", "literature", "geography", "philosophy", "psychology", "art", "music"],
        "movies": ["action", "comedy", "drama", "thriller", "horror", "romance", "sci-fi", "fantasy", "documentary", "animation"],
        "architecture": ["building", "skyscraper", "bridge", "house", "tower", "museum", "stadium", "temple", "palace"],
        "history": ["ancient", "medieval", "modern", "renaissance", "empire", "war", "battle", "civilization", "monarchy"],
        "travel": ["tourism", "vacation", "destination", "trip", "adventure", "tourist", "hotel", "plane ticket", "beach"],
        "science": ["physics", "chemistry", "biology", "astronomy", "medicine", "engineering", "mathematics", "genetics", "evolution"],
        "health": ["fitness", "nutrition", "medicine", "doctor", "hospital", "mental health", "exercise", "yoga", "sleep"],
        "animals": ["dog", "cat", "rabbit", "hamster", "parrot", "goldfish", "horse", "cow", "chicken", "sheep"],
        "politics": ["election", "government", "democracy", "vote", "senator", "parliament", "law", "president", "campaign", "debate"],
        "business": ["money", "office", "company", "startup", "economy", "investment", "bank", "stock", "finance", "entrepreneur"],
        "emotions": ["happy", "sad", "angry", "fear", "love", "hate", "joy", "surprise", "trust", "disgust"],
        "colors": ["red", "blue", "green", "yellow", "orange", "purple", "pink", "brown", "black", "white"],
        "jobs": ["teacher", "doctor", "engineer", "artist", "pilot", "chef", "nurse", "police", "firefighter", "developer"],
        "weather": ["rain", "snow", "storm", "sunny", "cloudy", "fog", "hail", "wind", "lightning", "thunder"],
        "weapons": ["gun", "sword", "knife", "bomb", "tank", "missile", "arrow", "rifle", "grenade", "cannon"],
        "fantasy creatures": ["dragon", "unicorn", "fairy", "elf", "dwarf", "giant", "goblin", "phoenix", "mermaid", "troll"],
        "languages": ["english", "spanish", "french", "chinese", "arabic", "russian", "japanese", "german", "hindi", "portuguese"],
        "countries": ["palestine", "usa", "china", "india", "germany", "brazil", "france", "japan", "russia", "uk", "canada"],
        "occupations": ["plumber", "electrician", "dentist", "scientist", "lawyer", "architect", "actor", "journalist", "mechanic", "cashier"],
        "tools": ["hammer", "screwdriver", "wrench", "pliers", "drill", "saw", "chisel", "tape measure", "level", "toolbox"],
        "space": ["planet", "star", "moon", "galaxy", "black hole", "spaceship", "astronaut", "telescope", "satellite", "comet"],
        "emojis": ["😊", "😂", "😍", "😢", "😡", "👍", "🙏", "🎉", "❤️", "🔥"],
        "holidays": ["christmas", "easter", "halloween", "thanksgiving", "new year", "valentine", "ramadan", "diwali", "hanukkah", "independence day"],
        "instruments": ["guitar", "piano", "violin", "drums", "flute", "trumpet", "saxophone", "cello", "clarinet", "harp"],
        "games": ["chess", "poker", "monopoly", "minecraft", "fortnite", "call of duty", "roblox", "tetris", "among us", "valorant"],
        "social media": ["facebook", "instagram", "twitter", "tiktok", "snapchat", "linkedin", "reddit", "youtube", "whatsapp", "discord"]
}

             
             
